src/platforms/MercadoPago/controllers/DefaultController.php
<?php

namespace quoma\checkout\platforms\MercadoPago\controllers;

use Yii;
use yii\web\Controller;
use quoma\checkout\platforms\MercadoPago\MercadoPago;
use quoma\checkout\models\WebPayment;
use quoma\checkout\models\Platform;
use quoma\checkout\models\Serialize;
use quoma\checkout\models\SiteData;
use quoma\checkout\models\Site;
use quoma\checkout\models\WebPaymentData;

class DefaultController extends Controller {

    public function init() {
        parent::init();
        //Agregado porq si no puedo enviarle post
    }

    public function actionCreatePreference($payment) {

        $this->layout = '//main_no_menu';

        $result = [];
        $items = [];

        $payment = WebPayment::find()->where(['uuid' => $payment])->one();

        if (!$payment) {
            throw new \yii\web\HttpException(400, Yii::t('yii', 'Your request is invalid: payment not found.'));
        }

        //chequeo si no ha superado el tiempo disponible para la operación
        if ($payment->isOnTimeout()) {
            return $this->render('_error', [
                        'message' => 'Lo sentimos! <br> Se ha agotado el tiempo disponible para realizar la operación. Por favor vuelva a intentarlo.',
                        'site' => $payment->site->name,
                        'operation' => $payment->uuid
            ]);
        }

        $mercadoPago = new MercadoPago();

        $site = \quoma\checkout\models\Site::findOne($payment->site_id);


        //TODO: recibir un listado de items para armar el detalle de un pago
        $items[] = [
            "title" => $payment->concept,
            "quantity" => 1,
            "currency_id" => "ARS",
            "unit_price" => $payment->pendingAmount,
            'picture_url' => \yii\helpers\Url::to('@web/images/site/' . $payment->site->image, true),
        ];

        $excluded_payment_methods = $site->getExcludedPaymentMethods($payment->platform_id);
        $payment_methods = [
            "excluded_payment_methods" => $excluded_payment_methods,
            "excluded_payment_types" => [],
        ];

        if ($payment->installments) {
            $payment_methods ['default_installments'] = (int) $payment->installments;
            $payment_methods ['installments'] = (int) $payment->installments;
        } else {
            $payment_methods ['installments'] = (int) $site->findInstallment();
        }

        $preference_data = [
            'id' => $payment->uuid,
            'external_reference' => $payment->uuid,
            "items" => $items,
            'additional_info' => $payment->concept,
            'payer' => [
                'name' => '',
                'surname' => '',
                'email' => '',
                'phone' => [
                    'number' => ''
                ],
                'address' => [
                    'street_name' => '',
                    'zip_code' => ''
                ]
            ],
            'auto_return' => 'approved',
            'payment_methods' => $payment_methods,
            "back_urls" => [
                "success" => $mercadoPago->getCallbackUrl(),
                "failure" => $mercadoPago->getCallbackUrl(),
                "pending" => $mercadoPago->getCallbackUrl()
            ],
        ];
        
        if($payment->expires){
            $expiration_date = $payment->getExpirationDateTo();
            if($expiration_date != NULL){
                $preference_data['expires'] = ($payment->expires == 1) ? true : false;
                $preference_data['expiration_date_to'] = $payment->getExpirationDateTo();
            }
        }
        
        try {
            $preference = $mercadoPago->getMercadoPago($site->site_id)->create_preference($preference_data);
            $url = $preference['response'][(\Yii::$app->params['mp_sandbox'] ? "sandbox_" : "") . 'init_point'];
        } catch (\Exception $ex) {
            throw new \yii\web\HttpException(400, Yii::t('yii', 'Payment broker error.'));
        }


        return $this->render('init', [
                    'preference' => $preference_data,
                    'payment' => $payment,
                    'url' => $url,
        ]);
    }

    public function actionCreatePreapprovalPayment($payment) {

        $this->layout = '//main_no_menu';

        $result = [];
        $items = [];

        $payment = WebPayment::find()->where(['uuid' => $payment])->one();

        if (!$payment) {
            throw new \yii\web\HttpException(400, Yii::t('yii', 'Your request is invalid: payment not found.'));
        }

        //chequeo si no ha superado el tiempo disponible para la operación
        if ($payment->isOnTimeout()) {
            return $this->render('_error', [
                        'message' => 'Lo sentimos! <br> Se ha agotado el tiempo disponible para realizar la operación. Por favor vuelva a intentarlo.',
                        'site' => $payment->site->name,
                        'operation' => $payment->uuid
            ]);
        }

        $mercadoPago = new MercadoPago();

        $site = \quoma\checkout\models\Site::findOne($payment->site_id);

        $url = $mercadoPago->getCallbackUrl() . "&site_id=$site->site_id";
        
        if(Yii::$app->params['testing']){
            $url = \Yii::$app->params['mp_back_url'] . "index.php?r=checkout_online/MercadoPago/default/back&site_id=$site->site_id";
        }
        $preapproval_data = [
            "payer_email" => $payment->payer_email,
            //debe ser una url publica
            "back_url" => $url,
            "reason" => $payment->reason,
            "external_reference" => uniqid('', true) . '-' . $payment->uuid,
            "auto_recurring" => array(
                "frequency" => $payment->frequency,
                "frequency_type" => $payment->frequency_type,
                "transaction_amount" => $payment->amount,
                "currency_id" => $payment->currency_id,
            )
        ];
        
        if ($payment->payment_start_date) {
            $preapproval_data['auto_recurring']['start_date'] = $payment->payment_start_date;
        }

        if ($payment->payment_end_date) {

            $preapproval_data['auto_recurring']['end_date'] = $payment->payment_end_date;
        }
       
        try {
            //creo la subscripción en Cobros
            $subscription = WebPayment::getSubscription($preapproval_data);
            $payment->subscription_id= $subscription->subscription_id;
            $payment->save(false,['subscription_id']);
           
            $preapproval = $mercadoPago->getMercadoPago($site->site_id)->create_preapproval_payment($preapproval_data);
            $url = $preapproval['response'][(\Yii::$app->params['mp_sandbox'] ? "sandbox_" : "") . 'init_point'];
        } catch (\Exception $ex) {
            $message = 'Payment broker error.';
            if (!YII_ENV_PROD) {
                $message .= ' ' . $ex->getMessage();
            }
            throw new \yii\web\HttpException(400, Yii::t('yii', $message));
        }

        return $this->render('init', [
                    'payment' => $payment,
                    'url' => $url,
        ]);
    }

    /**
     * Chequea el tiempo que el cliente se demoró en la vista de cobros para no enviar pagos que puedn superar el tiempo máximo de operación
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionCheckTime() {

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $json = [];

        if ($post = \Yii::$app->request->post()) {

            $web_payment = WebPayment::findOne($post['payment_id']);

            if (!$web_payment) {
                $json['status'] = 'error';
                $json['message'] = 'El pago no existe!';
                return $json;
            }

            //chequeo si no ha superado el tiempo disponible para la operación
            if ($web_payment->isOnTimeout()) {
                $web_payment->changeStatus('timeout');
                $this->notifyPaymentTimeOut($web_payment);
                $json['status'] = 'error';
                $json['html'] = $this->renderPartial('_error', [
                    'message' => 'Lo sentimos! <br> Se ha agotado el tiempo disponible para realizar la operación. Por favor vuelva a intentarlo.',
                    'site' => $web_payment->site->name,
                    'operation' => $web_payment->uuid
                ]);
                return $json;
            }

            $json['status'] = 'success';
            $json['message'] = 'OK';

            return $json;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    private function NotifyPaymentTimeOut($payment) {

        if (isset($payment->request_uuid))
            $nro_operation = $payment->request_uuid;
        else
            throw new \yii\web\HttpException(400, \Yii::t('yii', 'Your request is invalid.'));

        //open connection
        $ch = curl_init();

        //set the url, number of POST vars, POST data
        $url = str_replace('www.', '', $payment->result_url);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, ['data' => $nro_operation, 'status' => $payment->status]);

        if (\Yii::$app->params['testing']) {
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        }
        
        //execute post
        $result = curl_exec($ch);
        
        if ($result === false) {
            echo "Error: " . curl_error($ch);
            echo "\n";
        }
        //close connection
        curl_close($ch);
        
//        \Yii::$app->response->format = 'json';
        return [
            'status' => 'ok',
            'message' => '',
        ];
    }

    public function actionIndex() {
        return $this->render('index');

src/platforms/MercadoPago/views/default/_error.php
<h3 class="text-center text-danger"><?= $message ?></h3>

<div class="row">
    <div class="col-lg-12 text-center">
        <a id="back_button" class="button btn btn-primary send-form" href="<?= Yii::$app->urlManager->createUrl(['checkout_online/MercadoPago/default/back', 'external_reference' => $operation]) ?>">Volver a <?= $site ?></a>
    </div>
</div>

src/platforms/MercadoPago/views/default/init.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Payment */

$this->title = quoma\checkout\CheckoutModule::t('Pago');
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Payments'), 'url' => ['#']];
//$this->params['breadcrumbs'][] = $this->title;
?>


<div class="checkout-default-index">

    <div class="panel-body">

        <div id="column-content" class="col-lg-3 text-center">
            <img style="height: 120px" src="<?= yii\helpers\Url::to('@web/images/site/' . $payment->site->image, true) ?>" class="img-responsive inline-block">
        </div>
        <div class="col-lg-9" style="border-left: 2px solid #ccc;">
            <?php if ($payment->preapproval_payment): ?>

                <h3>
                    <?php
                    //TODO: implementar i18n a nivel plataforma
                    echo Yii::t('app', 'Monto Mensual');
                    ?>: $ <?php echo Yii::$app->formatter->asCurrency($payment->pendingAmount, 'ARG'); ?> 
                </h3>
                <span>Forma de pago:</span><h4>Débito automático</h4>
                <br>
                <a id="MP-Checkout" class="btn btn-success">Suscribirse y Pagar</a>
                <h6> Al presionar "Suscribirse y Pagar" lo redirigiremos a Mercado Pago.</h6>
                
                <br>
                
                <!--<a href="<?php // echo $url;  ?>" name="MP-Checkout" class="red-ar-l-rn-ArOn" mp-mode="redirect">Pagar</a>-->
                <h5>Dispone de <strong><span id="count-down" class="text-warning"></span></strong>  minutos para continuar. </h5>
            <?php else: ?>
                <h3>
                    <?php
                    //TODO: implementar i18n a nivel plataforma
                    echo Yii::t('app', 'Monto Total');
                    ?>: $ <?php echo Yii::$app->formatter->asCurrency($payment->pendingAmount, 'ARG'); ?> 
                </h3>
                <br>
                <a id="MP-Checkout" class="btn btn-success">Pagar</a>
                <h6> Al presionar "Pagar" lo redirigiremos a Mercado Pago.</h6>
                
                <br>
                
                <h5>Dispone de <strong><span id="count-down" class="text-warning"></span></strong>   minutos para continuar. </h5>

                <a href="https://www.mercadopago.com.ar/promociones" target="_blank">
                    Ver Promociones de Pago
                </a>
            <?php endif; ?>

        </div>

    </div>
    <?php if (!YII_ENV_PROD) { ?>
        <div id="request_uuid"><?php echo $payment->request_uuid; ?></div>
        <div id="cobros_url"><?php echo yii\helpers\Url::to(['/'], true); ?></div>
    <?php } ?>
</div>

<style>

    #column-content img {
        display: inline-block;
    }

</style>

<script>
    var Form = new function (event) {

        //cheque si no superó el tiempo establecido antes de enviar el pago a Decidir
        this.send = function (event) {

            $('#MP-Checkout').on('click', function () {

                checkTime();

            });
        };

        function checkTime() {

            var data = new Object;
            data.payment_id = <?= $payment->web_payment_id ?>;

            console.log(data.payment_id);
            $.ajax({
                url: '<?= yii\helpers\Url::toRoute(['default/check-time']); ?>',
                data: data,
                dataType: 'json',
                type: 'post'
            }).done(function (json) {
                if (json.status === 'success') {
                    $MPC.openCheckout({
                        url: "<?php echo $url; ?>",
                        mode: "redirect",
                    });
                } else {
                    $('.checkout-default-index').html(json.html);
                }
            });
        }
        ;

        var c = <?= Yii::$app->params['time_cobros'] - 1 ?>;
        var t;
        var timer_is_on = 0;

        this.startTime = function () {
            startCount();
        };

        function timedCount() {
            document.getElementById("count-down").innerHTML = c;

            if (c === 0) {
                console.log('c=0');

                stopCount();
                checkTime();
            }
            c = c - 1;
            t = setTimeout(function () {
                timedCount()
            }, 60000);
        }

        function startCount() {
            if (!timer_is_on) {
                timer_is_on = 1;
                timedCount();
            }
        }

        function stopCount() {
            clearTimeout(t);
            timer_is_on = 0;
        }

    };


</script>

<?php
$this->registerJs('Form.send();');
$this->registerJs("Form.startTime();");
$this->registerJsFile("https://mp-tools.mlstatic.com/buttons/render.js");