src/models/Site.php
<?php

namespace quoma\checkout\models;

use Yii;

/**
 * This is the model class for table "site".
 *
 * @property integer $site_id
 * @property string $name
 * @property string $server_name
 * @property string $status
 * @property integer $company_id
 * @property string $image
 * @property string $admin_email
 *
 * @property SiteHasInstallment[] $siteHasInstallments
 * @property Installment[] $installments
 * @property SiteHasPaymentMethod[] $siteHasPaymentMethods
 * @property PaymentMethod[] $paymentMethods
 * @property SiteHasPlatform[] $siteHasPlatforms
 * @property Platform[] $platforms
 * @property WebPayment[] $webPayments
 */
class Site extends \quoma\core\db\ActiveRecord {

    private $_installments;
    private $_paymentMethods;
    private $_platforms;

    /**
     * @var UploadedFile
     */
    public $imageFile;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'site';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb() {
        return Yii::$app->get('db_checkout');
    }

    /**
     * @inheritdoc
     */
    /*
      public function behaviors()
      {
      return [
      'timestamp' => [
      'class' => 'yii\behaviors\TimestampBehavior',
      'attributes' => [
      yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['timestamp'],
      ],
      ],
      'date' => [
      'class' => 'yii\behaviors\TimestampBehavior',
      'attributes' => [
      yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['date'],
      ],
      'value' => function(){return date('Y-m-d');},
      ],
      'time' => [
      'class' => 'yii\behaviors\TimestampBehavior',
      'attributes' => [
      yii\db\ActiveRecord::EVENT_BEFORE_INSERT => ['time'],
      ],
      'value' => function(){return date('h:i');},
      ],
      ];
      }
     */

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['status','admin_email'], 'string'],
            [['status', 'company_id', 'name', 'server_name','admin_email'], 'required'],
            [['company_id'], 'integer'],
            [['installments', 'paymentMethods', 'platforms'], 'safe'],
            [['name'], 'string', 'max' => 45],
            [['server_name'], 'string', 'max' => 100],
            [['image'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'platforms' => \quoma\checkout\CheckoutModule::t('Platforms'),
            'site_id' => \quoma\checkout\CheckoutModule::t('Site'),
            'name' => \quoma\checkout\CheckoutModule::t('Name'),
            'server_name' => \quoma\checkout\CheckoutModule::t('Server Name'),
            'status' => \quoma\checkout\CheckoutModule::t('Status'),
            'company_id' => \quoma\checkout\CheckoutModule::t('Company'),
            'company' => \quoma\checkout\CheckoutModule::t('Company'),
            'siteHasInstallments' => 'SiteHasInstallments',
            'installments' => 'Installments',
            'siteHasPaymentMethods' => 'SiteHasPaymentMethods',
            'paymentMethods' => 'PaymentMethods',
            'siteHasPlatforms' => 'SiteHasPlatforms',
            'platforms' => \quoma\checkout\CheckoutModule::t('Platforms'),
            'webPayments' => 'WebPayments',
            'admin_email' => \quoma\checkout\CheckoutModule::t('Admin Email'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteHasInstallments() {
        return $this->hasMany(SiteHasInstallment::className(), ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInstallments() {
        return $this->hasMany(Installment::className(), ['installment_id' => 'installment_id'])->viaTable('site_has_installment', ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteHasPaymentMethods() {
        return $this->hasMany(SiteHasPaymentMethod::className(), ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentMethods() {
        return $this->hasMany(PaymentMethod::className(), ['payment_method_id' => 'payment_method_id'])->viaTable('site_has_payment_method', ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentMethodTypes() {
        return $this->hasMany(PaymentMethodType::className(), ['payment_method_type_id' => 'payment_method_type_id'])->viaTable('payment_method_type_has_site', ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPaymentMethodTypeHasSite() {
        return $this->hasMany(PaymentMethodTypeHasSite::className(), ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteHasPlatforms() {
        return $this->hasMany(SiteHasPlatform::className(), ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlatforms() {
        return $this->hasMany(Platform::className(), ['platform_id' => 'platform_id'])->viaTable('site_has_platform', ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWebPayments() {
        return $this->hasMany(WebPayment::className(), ['site_id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany() {
        return $this->hasOne(\app\modules\sale\models\Company::className(), ['company_id' => 'company_id']);
    }

    /**
     * @brief Sets Installments relation on helper variable and handles events insert and update
     */
    public function setInstallments($installments, $platform_id) {

        if (empty($installments)) {
            $installments = [];
        }

        foreach ($installments as $id) {
            $this->link('installments', Installment::findOne($id), ['platform_id' => $platform_id]);
        }
    }

    /**
     * @brief Sets Installments relation on helper variable and handles events insert and update
     */
    public function setTimeOut($platform_id, $time_out) {

        $site_has_platform = SiteHasPlatform::findAll(['platform_id' => $platform_id, 'site_id' => $this->site_id]);

        if ($site_has_platform)
            foreach ($site_has_platform as $site_platform) {
                if ($site_platform->platform_id == $platform_id) {
                    $site_platform->time_out = $time_out;
                    $site_platform->save(['time_out']);
                }
            }
    }

    /**
     * @brief Sets PaymentMethods relation on helper variable and handles events insert and update
     */
    public function setTimeOutByPaymentMethodsTypes($paymentMethodsTypes, $platform_id) {

        if (empty($paymentMethodsTypes)) {
            $paymentMethodsTypes = [];
        }


        foreach ($paymentMethodsTypes as $method_type_id => $time_out) {
            if ($time_out) {
                $this->link('paymentMethodTypes', PaymentMethodType::findOne($method_type_id), ['platform_id' => $platform_id, 'time_out' => $time_out]);
            }
        }
    }

    /**
     * Elimina  las relaciones del sitio con installment
     */
    public function deleteInstallments() {
        $old_installments = Installment::find()->joinWith('siteHasInstallments', true)->where(['site_id' => $this->site_id])->all();

        if ($old_installments) {
            foreach ($old_installments as $model) {
                $this->unlink('installments', $model, true);
            }
        }
    }

    /**
     * @brief Sets PaymentMethods relation on helper variable and handles events insert and update
     */
    public function setPaymentMethods($paymentMethods, $platform_id) {

        if (empty($paymentMethods)) {
            $paymentMethods = [];
        }


        foreach ($paymentMethods as $id) {
            $this->link('paymentMethods', PaymentMethod::findOne($id), ['platform_id' => $platform_id]);
        }
    }

    /**
     * Elimina  las relaciones del sitio con installment
     */
    public function deletePaymentMethods() {
        $old_payment = PaymentMethod::find()->joinWith('siteHasPaymentMethods', true)->where(['site_id' => $this->site_id])->all();

        if ($old_payment) {
            foreach ($old_payment as $model) {
                $this->unlink('paymentMethods', $model, true);
            }
        }
    }

    /**
     * Elimina  las relaciones del sitio con installment
     */
    public function deletePaymentMethodTypes() {
        $old_methods_types = PaymentMethodType::find()->joinWith('paymentMethodTypeHasSites', true)->where(['site_id' => $this->site_id])->all();

        if ($old_methods_types) {
            foreach ($old_methods_types as $model) {
                $this->unlink('paymentMethodTypes', $model, true);
            }
        }
    }

    /**
     * Elimina  las relaciones del sitio con installment
     */
    public function deletePlatforms() {

        if ($this->platforms) {
            $this->unlinkAll('platforms', true);
        }
    }

    /**
     * @brief Sets Platforms relation on helper variable and handles events insert and update
     */
    public function setPlatforms($platforms) {

        if (empty($platforms)) {
            $platforms = [];
        }

        $this->_platforms = $platforms;

        $savePlatforms = function($event) {
            $this->unlinkAll('platforms', true);

            foreach ($this->_platforms as $id) {
                $this->link('platforms', Platform::findOne($id));
            }
        };

        $this->on(self::EVENT_AFTER_INSERT, $savePlatforms);
        $this->on(self::EVENT_AFTER_UPDATE, $savePlatforms);
    }

    /**
     * @inheritdoc

src/controllers/SiteController.php
<?php

namespace quoma\checkout\controllers;

use Yii;
use quoma\checkout\models\Site;
use quoma\checkout\models\search\SiteSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SiteController implements the CRUD actions for Site model.
 */
class SiteController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Site models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new SiteSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Site model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Site model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Site();

        if ($model->load(Yii::$app->request->post())) {

            $post = Yii::$app->request->post()['Site'];

            $rnd = uniqid();
            $uploadedFile = \yii\web\UploadedFile::getInstance($model, 'image');
            $fileName = "{$rnd}-{$uploadedFile}";  // random number + file name

            if (!empty($uploadedFile)) //si se ha cargado una imagen
                $model->image = $fileName; // le asignoa logo el nombre del archivo generado

            if ($model->validateRelations($post) && $model->save()) {

                if (!empty($uploadedFile)) //si se ha cargado una imagen
                    $uploadedFile->saveAs(Yii::$app->basePath . '/web/images/site/' . $fileName);  // image will uplode to rootDirectory/banner/


                if ($post['platforms_config']) {
                    foreach ($post['platforms_config'] as $platform_id => $data) {
                        $model->setInstallments($data['installments'], $platform_id);
                        $model->setPaymentMethods($data['payment_methods'], $platform_id);
                        $model->setTimeOut($platform_id, $data['time_out']);
                        $model->setTimeOutByPaymentMethodsTypes($data['time_outs_methods'], $platform_id);
                    }
                }

                return $this->redirect(['view', 'id' => $model->site_id]);
            }
        }
        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /*
     * 
     */

    public function actionGetConfig() {

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $json = [];

        if ($post = \Yii::$app->request->post()) {

            $installments = \quoma\checkout\models\Installment::find()->all();

            $payment_methods = \quoma\checkout\models\PaymentMethod::find()->where(['platform_id' => $post['select']])->all();

            $payment_method_types = \quoma\checkout\models\PaymentMethodType::find()->all();

            if (isset($post['site_id']))
                $site_has_platform = \quoma\checkout\models\SiteHasPlatform::findOne(['platform_id' => $post['select'], 'site_id' => $post['site_id']]);
            else
                $site_has_platform = NULL;

            $json['status'] = 'success';
            $json['platform_id'] = $post['select'];
            $json['html'] = $this->renderPartial('partials/_view', [
                'installments' => $installments,
                'payment_methods' => $payment_methods,
                'payment_method_types' => $payment_method_types,
                'platform_id' => $post['select'],
                'site_has_platform' => $site_has_platform,
                'site_id' => (isset($post['site_id'])) ? $post['site_id'] : NULL,
            ]);

            return $json;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Updates an existing Site model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $post = Yii::$app->request->post()['Site'];

            $rnd = uniqid();
            $uploadedFile = \yii\web\UploadedFile::getInstance($model, 'image');
            $fileName = "{$rnd}-{$uploadedFile}";  // random number + file name

            if (!empty($uploadedFile)) //si se ha cargado una imagen
                $model->image = $fileName; // le asignoa logo el nombre del archivo generado

            if ($model->validateRelations($post) && $model->save()) {

                if (!empty($uploadedFile)) //si se ha cargado una imagen
                    $uploadedFile->saveAs(Yii::$app->basePath . '/web/images/site/' . $fileName);  // image will uplode to rootDirectory/banner/


                    
//                $model->deletePlatforms();
                $model->deleteInstallments();
                $model->deletePaymentMethods();
                $model->deletePaymentMethodTypes();

                if ($post['platforms_config']) {
                    foreach ($post['platforms_config'] as $platform_id => $data) {
                        $model->setInstallments($data['installments'], $platform_id);
                        $model->setPaymentMethods($data['payment_methods'], $platform_id);

                        $model->setTimeOut($platform_id, $data['time_out']);
                        $model->setTimeOutByPaymentMethodsTypes($data['time_outs_methods'], $platform_id);
                    }
                }

                return $this->redirect(['view', 'id' => $model->site_id]);
            }
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Site model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {

        $model = $this->findModel($id);

        $model->deletePaymentMethods();
        $model->deletePaymentMethodTypes();
        $model->deleteInstallments();
        $model->deletePlatforms();

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Asignar una empresa de Arya a un sitio
     * @param integer $id Site_id
     * @return mixed
     */
    public function actionAssignCompany($id) {
        return $this->render('assign_company', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Site model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Site the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Site::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

src/views/site/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Site */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="site-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'admin_email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'server_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->dropDownList([ 'enabled' => quoma\checkout\CheckoutModule::t('Enabled'), 'disabled' => quoma\checkout\CheckoutModule::t('Disabled'),]) ?>

    <?= $form->field($model, 'company_id')->dropDownList(\yii\helpers\ArrayHelper::map(\app\modules\sale\models\Company::find()->where('status="enabled"')->all(), 'company_id', 'name'), ['prompt' => 'Seleccione en caso de que desee facturar desde este sitio']) ?>


    <?=
    $form->field($model, 'platforms')->checkboxList(
            \yii\helpers\ArrayHelper::map(
                    \quoma\checkout\models\Platform::find()->where('status="enabled"')->all(), 'platform_id', 'name'
            ), [
        'item' => function ($index, $label, $name, $checked, $value) use ($model) {
            return Html::checkbox($name, (in_array($value, $model->fillPlataforms()) ? true : false), [
                        'value' => $value,
                        'label' => $label,
                        'data-target' => 'view-' . $value,
                        'class' => 'check_platform',
                    ]) . '<br/>'
                    . '<div id="view_' . $value . '"></div>';
        }
                    ], [
                'encode' => false,
                    ]
            );
            ?>


            <div class="form-group<?php if ($model->hasErrors('paymentMethods')) echo ' has-error' ?>">



            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Imagen</h3>
                </div>
                <div class="panel-body">

                    <div class="row">
                        <div class="col-lg-12">

                            <?php if (!$model->isNewRecord && !empty($model->image)): ?>
                                <div class="col-lg-12">
                                    <table class="table table-responsive detail-view">
                                        <thead>
                                            <tr>
                                                <td class="col-lg-6"><img src="<?= yii\helpers\Url::to('@web/images/site/' . $model->image, true) ?>" alt="" style="width: 80%" class="img-rounded"></td>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            <?php endif; ?>

                            <?php
                            echo \kartik\file\FileInput::widget([
                                'name' => 'Site[image]',
                                'options' => [
                                    'multiple' => false
                                ],
                                'pluginOptions' => [
//                        'maxFileCount' => 10,
                                    'showUpload' => false
                                ]
                            ]);
                            ?>
                        </div>
                    </div>

                </div>
            </div>

            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>

        <script>



            var Platforms = new function () {

                this.init = function () {

                    $(document).ready(function () {

                        $("input:checkbox[class=check_platform]:checked").each(function () {

                            var data = new Object;
                            data.select = $(this).val();
                            data.site_id = <?= ($model->site_id) ? $model->site_id : NULL ?>

                            $.ajax({
                                url: '<?= yii\helpers\Url::toRoute(['site/get-config']); ?>',
                                data: data,
                                dataType: 'json',
                                type: 'post'
                            }).done(function (json) {
                                if (json.status === 'success') {
                                    var name = '#view_' + json.platform_id;
                                    $(name).html(json.html);
                                }
                            });
                        });
                    });
                };

                this.change = function (event) {
                    $('.check_platform').on('change', function () {

                        var data = new Object;
                        data.select = $(this).val();

                        if ($(this).is(':checked')) {

                            $.ajax({
                                url: '<?= yii\helpers\Url::toRoute(['site/get-config']); ?>',
                                data: data,
                                dataType: 'json',
                                type: 'post'
                            }).done(function (json) {

                                if (json.status === 'success') {
                                    var name = '#view_' + json.platform_id;
                                    $(name).html(json.html);
                                }
                            });
                        } else {
                            var name = '#view_' + data.select;
                            $(name).html('');
                        }

                    });
                };

                this.methods_type = function (platform) {
                
                    $('.detail_methods').on('change', function () {
                        
                        var id = $(this).attr('data-id');
                       
                        if ($(this).is(':checked')) {

                            $('#methods_types_'+id).show();

                        } else {
                            $('#methods_types_'+id).hide();
                        }

                    });
                };
            };


        </script>

        <?php
        $this->registerJs('Platforms.init();');
        $this->registerJs('Platforms.change();');
        $this->registerJs('Platforms.methods_type();');

        

src/views/site/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\search\SiteSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="site-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'site_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'server_name') ?>

    <?= $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/views/site/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Site */

$this->title = Yii::t('app', 'Create').' '. quoma\checkout\CheckoutModule::t('Site');
$this->params['breadcrumbs'][] = ['label' => quoma\checkout\CheckoutModule::t('Sites'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use quoma\checkout\CheckoutModule;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\checkout\models\search\SiteSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = CheckoutModule::t('Sites');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">
    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <p>
            <?= Html::a("<span class='glyphicon glyphicon-plus'></span> " . Yii::t('app', 'Create') . ' ' . 
                    CheckoutModule::t('Site'), ['create'], ['class' => 'btn btn-success']) ?>
        </p>
    </div>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name',
            'server_name',
            [
                'attribute' => 'status',
                'value' => function($data) {
                    return (!empty($data->status) ) ? $data->getLabelStatus() : '-';
                },
                'filter' => \quoma\checkout\models\Site::getStatus(),
            ],
            ['class' => 'quoma\core\grid\ActionColumn'],
        ],
    ]);
    ?>

</div>

src/views/site/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Site */

$this->title = Yii::t('app', 'Update') .' '. quoma\checkout\CheckoutModule::t('Site'). ' ' . $model->name;

$this->params['breadcrumbs'][] = ['label' => quoma\checkout\CheckoutModule::t('Site'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->site_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="site-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/views/site/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\checkout\models\Site */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => quoma\checkout\CheckoutModule::t('Sites'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-view">
    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a("<span class='glyphicon glyphicon-pencil'></span> " . Yii::t('app', 'Update'),
                    ['update', 'id' => $model->site_id], ['class' => 'btn btn-primary']) ?>
            <?php if($model->deletable)
                echo Html::a("<span class='glyphicon glyphicon-remove'></span> " . Yii::t('app', 'Delete'), ['delete', 'id' => $model->site_id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
        </p>
    </div>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'admin_email',
            'server_name',
            [
                'attribute'=>'status',
                'value'=> (!empty($model->status) ) ? $model->getLabelStatus() : '-',
            ],
            [
                'label' => 'Imagen',
                'attribute' => 'image',
//                'value' => Yii::$app->getModule('equipment')->basePath . $model->image,
                'value' =>  yii\helpers\Url::to('@web/images/site/'.$model->image, true),
                'format' => ['image',['width'=>'500','height'=>'500']],
                'visible' => ($model->image) ? true : false
            ],
        ],
    ]) ?>

</div>